spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: task-service
          uri: http://localhost:8083
          predicates:
            - Path=/tasks/**

  application:
    name: api-gateway

server:
  port: 8080