version: '3.8'

services:
  postgres-authdb:
    image: postgres:15
    container_name: postgres-authdb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth-data:/var/lib/postgresql/data
      - ./auth-service/src/main/resources/database/dev/postgresql-config.yml:/docker-entrypoint-initdb.d/postgresql-config.yml

volumes:
  postgres_auth-data:
