version: '3.8'

services:
  postgres-userdb:
    image: postgres:15
    container_name: postgres-userdb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_user-data:/var/lib/postgresql/data
      - ./task-service/src/main/resources/database/dev/postgresql-config.yml:/docker-entrypoint-initdb.d/postgresql-config.yml

volumes:
  postgres_user-data:
